include:
  - board: seeeduino_xiao_ble
    shield: chocofi_dongle prospector_adapter
  # - board: seeeduino_xiao_ble
  #   shield: settings_reset
  - board: nice_nano_v2
    shield: chocofi_left # nice_view_adapter nice_view
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
  - board: nice_nano_v2
    shield: chocofi_right # nice_view_adapter nice_view
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
  # - board: nice_nano_v2
  #   shield: settings_reset
